"""
YOLOv8 Nano Inference Engine on Cropped ROI
Author: Dhivyashree G J. (24BCE1516)

Executes YOLOv8n object detection selectively on the dynamically cropped ROI
generated by Stage 1 ToF depth gating. Translates local ROI detection coordinates
back into full-frame coordinates and filters for navigation hazard classes.
"""

from dataclasses import dataclass
import time
from typing import List, Optional, Tuple
import numpy as np

import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
import config
from module2_vision.class_map import ClassMap, HazardSeverity

# Optional Ultralytics YOLO import
try:
    from ultralytics import YOLO
    ULTRALYTICS_AVAILABLE = True
except ImportError:
    YOLO = None
    ULTRALYTICS_AVAILABLE = False


@dataclass
class Detection:
    """Represents a validated obstacle detection with semantic hazard attributes."""
    class_id: int
    class_name: str
    confidence: float
    local_box: Tuple[int, int, int, int]    # (lx1, ly1, lx2, ly2) relative to ROI
    global_box: Tuple[int, int, int, int]   # (gx1, gy1, gx2, gy2) relative to full frame
    hazard_info: HazardSeverity


class YOLOEngine:
    """
    YOLOv8 Nano inference pipeline optimized for Raspberry Pi 4 edge execution.
    Runs strictly on cropped ROIs to minimize neural compute overhead.
    """

    def __init__(
        self,
        model_name: str = config.YOLO_MODEL_NAME,
        confidence_threshold: float = config.YOLO_CONFIDENCE_THRESHOLD,
        img_size: int = config.YOLO_IMG_SIZE,
        force_simulation: bool = False,
    ):
        self.model_name = model_name
        self.confidence_threshold = confidence_threshold
        self.img_size = img_size
        self.force_simulation = force_simulation or config.SIMULATION_MODE

        self.model = None
        self.is_real_model_loaded = False
        self.target_classes = ClassMap.get_coco_ids()

        self._load_model()

    def _load_model(self):
        """Loads Ultralytics YOLOv8n if available; otherwise enables simulation backend."""
        if not self.force_simulation and ULTRALYTICS_AVAILABLE and YOLO is not None:
            try:
                print(f"[YOLOEngine] Loading pretrained weights: {self.model_name}...")
                self.model = YOLO(self.model_name)
                self.is_real_model_loaded = True
                print("[YOLOEngine] Pretrained YOLOv8n initialized successfully.")
                return
            except Exception as e:
                print(f"[YOLOEngine] Notice: Real YOLO load failed ({e}). Falling back to simulation.")

        self.is_real_model_loaded = False
        self.model = None

    def infer_roi(
        self,
        cropped_roi: np.ndarray,
        roi_box: Tuple[int, int, int, int],
        elevation_hint: Optional[str] = None,
    ) -> List[Detection]:
        """
        Performs object detection inference on the cropped sub-image.
        
        Args:
            cropped_roi: Cropped sub-image (H_roi, W_roi, 3)
            roi_box: (rx1, ry1, rx2, ry2) bounding coordinates of ROI in full frame
            elevation_hint: "HeadHazard" or "GroundObstacle" from ToF
        
        Returns:
            List of validated Detection instances.
        """
        rx1, ry1, rx2, ry2 = roi_box
        roi_h, roi_w = cropped_roi.shape[:2]

        if roi_h < 10 or roi_w < 10:
            return []

        # Real inference if Ultralytics model is active
        if self.is_real_model_loaded and self.model is not None:
            return self._infer_ultralytics(cropped_roi, rx1, ry1, elevation_hint)

        # High-fidelity simulation inference fallback
        return self._infer_simulation(cropped_roi, rx1, ry1, roi_w, roi_h, elevation_hint)

    def _infer_ultralytics(
        self,
        roi: np.ndarray,
        offset_x: int,
        offset_y: int,
        elevation_hint: Optional[str],
    ) -> List[Detection]:
        """Executes actual PyTorch/Ultralytics YOLO forward pass."""
        detections: List[Detection] = []
        try:
            # Run inference on cropped sub-image with class filtering
            results = self.model(
                roi,
                classes=self.target_classes,
                conf=self.confidence_threshold,
                imgsz=self.img_size,
                verbose=False,
            )

            for r in results:
                boxes = r.boxes
                for box in boxes:
                    cls_id = int(box.cls[0].item())
                    conf = float(box.conf[0].item())
                    lx1, ly1, lx2, ly2 = map(int, box.xyxy[0].tolist())

                    # Translate local ROI coordinates back to full frame
                    gx1 = offset_x + lx1
                    gy1 = offset_y + ly1
                    gx2 = offset_x + lx2
                    gy2 = offset_y + ly2

                    cls_name = config.TARGET_COCO_CLASSES.get(cls_id, f"obj_{cls_id}")
                    hazard_info = ClassMap.resolve_hazard(cls_id, elevation_hint)

                    detections.append(
                        Detection(
                            class_id=cls_id,
                            class_name=cls_name,
                            confidence=round(conf, 3),
                            local_box=(lx1, ly1, lx2, ly2),
                            global_box=(gx1, gy1, gx2, gy2),
                            hazard_info=hazard_info,
                        )
                    )
            # Sort by highest confidence first
            detections.sort(key=lambda d: d.confidence, reverse=True)
        except Exception as e:
            print(f"[YOLOEngine] Inference error: {e}")

        return detections

    def _infer_simulation(
        self,
        roi: np.ndarray,
        offset_x: int,
        offset_y: int,
        roi_w: int,
        roi_h: int,
        elevation_hint: Optional[str],
    ) -> List[Detection]:
        """
        Simulated inference engine producing realistic detections based on scene,
        aspect ratio, and elevation clues, enabling rapid testing without GPU/PyTorch.
        """
        detections: List[Detection] = []

        # Discern obstacle class based on physical elevation and geometry
        if elevation_hint == "HeadHazard":
            cls_id = 0  # person
            cls_name = "person"
        elif elevation_hint == "GroundObstacle":
            # Wide ground obstacle -> vehicle; Tall/narrow -> bicycle
            if roi_w > int(roi_h * 1.1):
                cls_id = 2  # car
                cls_name = "car"
            else:
                cls_id = 1  # bicycle
                cls_name = "bicycle"
        else:
            cls_id = 0  # default pedestrian
            cls_name = "person"

        hazard = ClassMap.resolve_hazard(cls_id, elevation_hint)

        # Centered synthetic box inside the ROI
        margin_x = int(roi_w * 0.1)
        margin_y = int(roi_h * 0.1)
        lx1 = margin_x
        ly1 = margin_y
        lx2 = max(lx1 + 10, roi_w - margin_x)
        ly2 = max(ly1 + 10, roi_h - margin_y)

        gx1 = offset_x + lx1
        gy1 = offset_y + ly1
        gx2 = offset_x + lx2
        gy2 = offset_y + ly2

        detections.append(
            Detection(
                class_id=cls_id,
                class_name=cls_name,
                confidence=0.88,
                local_box=(lx1, ly1, lx2, ly2),
                global_box=(gx1, gy1, gx2, gy2),
                hazard_info=hazard,
            )
        )
        return detections
